version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo update npm
      - npm update -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo install dependencies
      - yarn
  build:
    commands:
      - echo build
      - yarn build
  post_build:
    commands:
      - echo build finished
artifacts:
  files:
    - dist/**/*
    - appspec.yml
