version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo update npm
      - npm update -g npm
      - echo npm -v
      - npm -v
  pre_build:
    commands:
      - echo install dependencies
      - npm install
  build:
    commands:
      - echo build
      - npm run build
  post_build:
    commands:
      - echo build finished
artifacts:
  files:
    - dist/**/*
    - appspec.yml
