version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo install yarn
      - npm i yarn -g
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
  build:
    commands:
      - echo build start
      - yarn build
      - echo build completed
artifacts:
  files:
    - dist/**/*
    - appspec.yml
