version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo install yarn
      - npm install -g yarn
  pre_build:
    commands:
      - echo install dependencies
      - yarn
  build:
    commands:
      - echo build
      - yarn build
  post_build:
    commands:
      - echo build finish
artifacts:
  files:
    - dist/**/*
    - appspec.yml
