version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo update npm
      - npm i npm@latest -g
      - echo install vue-cli
      - npm i @vue/cli -g
  pre_build:
    commands:
      - echo install dependencies
      - npm install
  build:
    commands:
      - echo build
      - npm run build
  post_build:
    commands:
      - echo build finished
artifacts:
  files:
    - dist/**/*
    - appspec.yml
